FROM official/golang:1.25.4 AS gobuild

WORKDIR /go-sqlite-server/

COPY go-sqlite-server/ ./

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod init url-shortener/sql-server && go mod tidy

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -ldflags="-s -w" -o sql-server

FROM official/node:18-alpine AS urls

COPY --from=gobuild /go-sqlite-server/sql-server /sql-server

WORKDIR /url-shortener

COPY package*.json ./

RUN --mount=type=cache,target=/url-shortener/.npm \
    npm set cache /url-shortener/.npm && \
    npm ci

COPY  static/ ./static

COPY server.js .

CMD ["sh", "-c", "/sql-server & node server.js"]
